### ISSUE TITLE
Examples broken?

### ISSUE THREAD

**Issue by e-dub** [KratosMultiphysics/GiDInterface#323]
Running the newest commit of Kratos and GiDInterface with GiD 13.1.11d.  Tried the structural 2d and 3d example cantilever truss and I get the following error:

```
Traceback (most recent call last):
  File "MainKratos.py", line 84, in <module>
    solver.Initialize()
  File "/kratos/applications/StructuralMechanicsApplication/python_scripts/structural_mechanics_static_solver.py", line 63, in Initialize
    super(StaticMechanicalSolver, self).Initialize() # The mechanical solver is created here.
  File "/kratos/applications/StructuralMechanicsApplication/python_scripts/structural_mechanics_solver.py", line 227, in Initialize
    mechanical_solution_strategy.Initialize()
RuntimeError: Error: No degrees of freedom!
```

**Comment by loumalouomega** [comment]
The interface is not writing the model parts in the json, look at #321

**Comment by e-dub** [comment]
As there is already an issue to this, closing...
