### ISSUE TITLE
FSI bug on MOK 2D

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/GiDInterface#426]
When executing MOK 2D:

```
Traceback (most recent call last):
  File "MainKratos.py", line 34, in <module>
    simulation.Run()
  File "E:\PROYECTOS\KratosGiD\kratos.gid\exec\kratos\kratos\python_scripts\analysis_stage.py", line 48, in Run
    self.RunSolutionLoop()
  File "E:\PROYECTOS\KratosGiD\kratos.gid\exec\kratos\kratos\python_scripts\analysis_stage.py", line 59, in RunSolutionLoop
    self._GetSolver().SolveSolutionStep()
  File "E:\PROYECTOS\KratosGiD\kratos.gid\exec\kratos\applications\FSIapplication\python_scripts\partitioned_fsi_base_solver.py", line 258, in SolveSolutionStep
    self._SolveMeshAndFluid()
  File "E:\PROYECTOS\KratosGiD\kratos.gid\exec\kratos\applications\FSIapplication\python_scripts\partitioned_fsi_dirichlet_neumann_solver.py", line 146, in _SolveMeshAndFluid
    self.fluid_solver.SolveSolutionStep()
  File "E:\PROYECTOS\KratosGiD\kratos.gid\exec\kratos\applications\FluidDynamicsApplication\python_scripts\fluid_solver.py", line 114, in SolveSolutionStep
    is_converged = self.solver.SolveSolutionStep()
RuntimeError: Error: Zero aggregates found.

in kratos/solving_strategies/builder_and_solvers/residualbased_block_builder_and_solver.h:369:ResidualBasedBlockBuilderAndSolver<class UblasSpace<double,class boost::numeric::ublas::compressed_matrix<...>,class boost::numeric::Vector >,...>::SystemSolveWithPhysics
   kratos/solving_strategies/builder_and_solvers/residualbased_block_builder_and_solver.h:413:ResidualBasedBlockBuilderAndSolver<class UblasSpace<double,class boost::numeric::ublas::compressed_matrix<...>,class boost::numeric::Vector >,...>::BuildAndSolve
```

**Comment by rubenzorrilla** [comment]
I think that we solved that
