### ISSUE TITLE
Setting addition instead of assignation in the Boundary Conditions

### ISSUE THREAD

**Issue by josep-m-carbonell** [KratosMultiphysics/GiDInterface#430]
In some cases the condition must add the value to the current value of the variable. 
The question is how to set in the tree that the BC value must be added instead of overwritten.

**Comment by jginternational** [comment]
If you need the user to decide which values must be added and which must overwrite the existent, you can add a boolean parameter (or a combo if there are more options) to the process and the user will choose.

If you don't want the user to choose it, then is the python process the one that should implement that logic .

**Comment by josep-m-carbonell** [comment]
The user must select this option. Add or Overwrite, which other options do you think about?

**Comment by jginternational** [comment]
I was thinking in some kind of priority scale, but maybe it's too much.

You can try and add yourself the parameter in the process

**Comment by josep-m-carbonell** [comment]
It is a good idea, well the priority is the order in which they are defined, the best way would be to be able to interchange the order of the process in the menu's tree.
Right now, the combo can have different options for the compound assign: Assign, Addition, Subtraction, Multiplication, Division. The default is Assign.

**Comment by jginternational** [comment]
This has been implemented in the problemtype but can not be used in master branch of kratos yet

it fails:

```
Traceback (most recent call last):
  File "MainKratos.py", line 7, in <module>
    MainSolid.Solution().Run()
  File "E:\PROYECTOS\KratosGiD\kratos.gid\exec\kratos\applications\SolidMechanicsApplication\python_scripts\MainSolid.py", line 52, in Run
    self.Initialize()
  File "E:\PROYECTOS\KratosGiD\kratos.gid\exec\kratos\applications\SolidMechanicsApplication\python_scripts\MainSolid.py", line 72, in Initialize
    self.processes = self._get_processes()
  File "E:\PROYECTOS\KratosGiD\kratos.gid\exec\kratos\applications\SolidMechanicsApplication\python_scripts\MainSolid.py", line 353, in _get_processes
    return (process_handler.ProcessHandler(domain_model, processes_parameters))
  File "E:\PROYECTOS\KratosGiD\kratos.gid\exec\kratos\applications\SolidMechanicsApplication\python_scripts\process_handler.py", line 35, in __init__
    self.Sort()
  File "E:\PROYECTOS\KratosGiD\kratos.gid\exec\kratos\applications\SolidMechanicsApplication\python_scripts\process_handler.py", line 110, in Sort
    self.list_of_processes  = self.ConstructList( self.ConstraintsList() )
  File "E:\PROYECTOS\KratosGiD\kratos.gid\exec\kratos\applications\SolidMechanicsApplication\python_scripts\process_handler.py", line 177, in ConstructList
    unsorted_process_list.append(self.ConstructProcess(process))
  File "E:\PROYECTOS\KratosGiD\kratos.gid\exec\kratos\applications\SolidMechanicsApplication\python_scripts\process_handler.py", line 167, in ConstructProcess
    return(python_module.Factory(process, self.Model))
  File "E:\PROYECTOS\KratosGiD\kratos.gid\exec\kratos\applications\SolidMechanicsApplication\python_scripts\assign_vector_components_to_nodes_process.py", line 13, in Factory
    return AssignVectorComponentsToNodesProcess(Model, custom_settings["Parameters"])
  File "E:\PROYECTOS\KratosGiD\kratos.gid\exec\kratos\applications\SolidMechanicsApplication\python_scripts\assign_vector_components_to_nodes_process.py", line 35, in __init__
    self.settings.ValidateAndAssignDefaults(default_settings)
RuntimeError: Error: ******************************************************************************************************
the item with name "compound_assignment" is present in this Parameters but NOT in the default values
******************************************************************************************************
hence Validation fails
parameters being validated are : 
{
    "model_part_name": "DISPLACEMENT_Constraint",
    "variable_name": "DISPLACEMENT",
    "value": [
        0.0,
        0.0,
        0.0
    ],
    "compound_assignment": "direct",
    "interval": [
        0.0,
        "End"
    ]
}
defaults against which the current parameters are validated are :
{
    "help": "This process assigns a vector value to a vector variable component by component",
    "model_part_name": "MODEL_PART_NAME",
    "variable_name": "VARIABLE_NAME",
    "value": [
        0.0,
        0.0,
        0.0
    ],
    "constrained": true,
    "interval": [
        0.0,
        "End"
    ],
    "local_axes": {}
}



in kratos/includes/kratos_parameters.h:637:Parameters::ValidateAndAssignDefaults
   kratos/includes/kratos_parameters.h:696:Parameters::ValidateAndAssignDefaults
```

**Comment by josep-m-carbonell** [comment]
Ok, yes, the changes are in the solid/develop I will make a PR to merge them into master
