### ISSUE TITLE
Conjugate heat transfer Example 2D fails

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/GiDInterface#774]
The 2D Conjugate Heat Transfer example Heated square fails at ->
```
Traceback (most recent call last):
  File "C:\Users\garat\Desktop\CHT example.gid\MainKratos.py", line 34, in <module>
    simulation.Run()
  File "E:\PROYECTOS\KratosGiD\kratos.gid\exec\kratos\KratosMultiphysics\analysis_stage.py", line 49, in Run
    self.Initialize()
  File "E:\PROYECTOS\KratosGiD\kratos.gid\exec\kratos\KratosMultiphysics\analysis_stage.py", line 84, in Initialize
    self._GetSolver().PrepareModelPart()
  File "E:\PROYECTOS\KratosGiD\kratos.gid\exec\kratos\KratosMultiphysics\ConvectionDiffusionApplication\conjugate_heat_transfer_solver.py", line 273, in PrepareModelPart
    self.fluid_solver.PrepareModelPart()
  File "E:\PROYECTOS\KratosGiD\kratos.gid\exec\kratos\KratosMultiphysics\FluidDynamicsApplication\fluid_solver.py", line 89, in PrepareModelPart
    self._ExecuteCheckAndPrepare()
  File "E:\PROYECTOS\KratosGiD\kratos.gid\exec\kratos\KratosMultiphysics\FluidDynamicsApplication\fluid_solver.py", line 216, in _ExecuteCheckAndPrepare
    check_and_prepare_model_process_fluid.CheckAndPrepareModelProcess(self.main_model_part, prepare_model_part_settings).Execute()
  File "E:\PROYECTOS\KratosGiD\kratos.gid\exec\kratos\KratosMultiphysics\FluidDynamicsApplication\check_and_prepare_model_process_fluid.py", line 73, in Execute
    KratosMultiphysics.TetrahedralMeshOrientationCheck(fluid_computational_model_part,throw_errors, flags).Execute()
RuntimeError: Error: Found a condition without any corresponding element. ID of condition = 57


in kratos/processes/tetrahedral_mesh_orientation_check.cpp:190:TetrahedralMeshOrientationCheck::Execute
   kratos/processes/tetrahedral_mesh_orientation_check.cpp:208:TetrahedralMeshOrientationCheck::Execute

```

[CHT example.gid.zip](https://github.com/KratosMultiphysics/GiDInterface/files/5573598/CHT.example.gid.zip)

**Comment by rubenzorrilla** [comment]
This says that there is a condition with no parent, which means that we have hanging lines with no surface entity associated to them.

**Comment by jginternational** [comment]
Ok, I've detected the problem. It's geometrically broken. Groups have the wrong lines.
