### ISSUE TITLE
Swimming dem example error

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/GiDInterface#783]
hi DEM swimmers !

Please check the branch release/Release-8.1
In the example ->
![image](https://user-images.githubusercontent.com/5918085/101022309-842c3b80-3571-11eb-944f-6a5fc559b86b.png)

I'm getting this error-> 
```
Traceback (most recent call last):
  File "MainKratos.py", line 39, in <module>
    simulation.Run()
  File "E:\PROYECTOS\KratosGiD\kratos.gid\exec\kratos\KratosMultiphysics\SwimmingDEMApplication\swimming_DEM_analysis.py", line 198, in Run
    super().Run()
  File "E:\PROYECTOS\KratosGiD\kratos.gid\exec\kratos\KratosMultiphysics\analysis_stage.py", line 50, in Run
    self.RunSolutionLoop()
  File "E:\PROYECTOS\KratosGiD\kratos.gid\exec\kratos\KratosMultiphysics\analysis_stage.py", line 67, in RunSolutionLoop
    is_converged = self._GetSolver().SolveSolutionStep()
  File "E:\PROYECTOS\KratosGiD\kratos.gid\exec\kratos\KratosMultiphysics\SwimmingDEMApplication\swimming_DEM_solver.py", line 358, in SolveSolutionStep
    self.SolveDEM()
  File "E:\PROYECTOS\KratosGiD\kratos.gid\exec\kratos\KratosMultiphysics\SwimmingDEMApplication\swimming_DEM_solver.py", line 403, in SolveDEM
    self.SolveDEMSolutionStep()
  File "E:\PROYECTOS\KratosGiD\kratos.gid\exec\kratos\KratosMultiphysics\SwimmingDEMApplication\swimming_DEM_solver.py", line 373, in SolveDEMSolutionStep
    self.dem_solver.SolveSolutionStep()
  File "E:\PROYECTOS\KratosGiD\kratos.gid\exec\kratos\KratosMultiphysics\DEMApplication\sphere_strategy.py", line 377, in SolveSolutionStep
    (self.cplusplus_strategy).SolveSolutionStep()
RuntimeError: Error: vector too long



in C:/KratosSource/applications/DEMApplication/custom_utilities/omp_dem_search.h:213:OMP_DEMSearch::SearchElementsInRadiusExclusiveImplementation
   C:/KratosSource/applications/DEMApplication/custom_strategies/strategies/explicit_solver_strategy.cpp:1469:ExplicitSolverStrategy::SearchNeighbours
   C:/KratosSource/applications/DEMApplication/custom_strategies/strategies/explicit_solver_strategy.cpp:505:ExplicitSolverStrategy::SearchDEMOperations
   C:/KratosSource/applications/SwimmingDEMApplication/custom_strategies/strategies/adams_bashforth_strategy.cpp:64:AdamsBashforthStrategy::SolveSolutionStep
```

I attach here the example

[demfluid.gid.zip](https://github.com/KratosMultiphysics/GiDInterface/files/5636261/demfluid.gid.zip)

Please help me so I can include this app in the release!

@GuillermoCasas @jgonzalezusua

**Comment by jgonzalezusua** [comment]
Hi @jginternational, in Kratos master branch I did not have this problem. Could you merge the master to this branch? Anyway I will run the case in this branch to see if there is any error.

**Comment by maceligueta** [comment]
The error 'vector too long' was encountered by @AlejandroCornejo long time ago. 
If I remember correctly, it was due to 0 or negative radius in some particles. I hope he can comment on this.

**Comment by AlejandroCornejo** [comment]
> The error 'vector too long' was encountered by @AlejandroCornejo long time ago.
> If I remember correctly, it was due to 0 or negative radius in some particles. I hope he can comment on this.

That's right. It happened to me a few years ago and it was due to a negative Radius.

**Comment by jginternational** [comment]
It could be, but not in the mdpa. It could be on the spheres created by the inlet
